- id: '1628758459344'
  alias: '베스틴 쿠키 갱신'
  description: ''
  trigger:
  - platform: time
    at: '00:00:01'
  condition:
    condition: template
    value_template: "{{ now().day == 1 }}"
  action:
    service: shell_command.cookie_phpsessid
  mode: single